### ISSUE TITLE
请求如果阿里云的短信短信模版id在哪里设置

### ISSUE THREAD

**Issue by qinkangdeid** [TheBund1st/daming#25]
最近要做短信发送的业务，查看到了这个项目，真的很棒 查看代码中 发现很多配置可以注入 但是看到自动配置的时候 阿里云的实现以下两个参数没看到是在哪里设置的 可否解答一下？感谢大佬提供的开箱即用的服务构思。🙏

![image](https://user-images.githubusercontent.com/17582522/70418380-3552df80-1a9e-11ea-9bad-3cc1dbec9ad9.png)

**Comment by Hippoom** [comment]
你好。

这两个参数可以通过`daming.aliyun.sms.`来注入。可以查看`AliyunSmsConfigurationTest`的`it should provide a AliyunSmsVerificationSender instance given sms provider is aliyun`测试作为参考，点此[前往](https://github.com/TheBund1st/daming/blob/a540de386cf31a49d51390456c7bc3b5c8b8aa7b/sms-verification-core/src/test/groovy/com/thebund1st/daming/boot/aliyun/sms/AliyunSmsConfigurationTest.groovy#L47)

**Comment by qinkangdeid** [comment]
> 你好。
> 
> 这两个参数可以通过`daming.aliyun.sms.`来注入。可以查看`AliyunSmsConfigurationTest`的`it should provide a AliyunSmsVerificationSender instance given sms provider is aliyun`测试作为参考，点此[前往](https://github.com/TheBund1st/daming/blob/a540de386cf31a49d51390456c7bc3b5c8b8aa7b/sms-verification-core/src/test/groovy/com/thebund1st/daming/boot/aliyun/sms/AliyunSmsConfigurationTest.groovy#L47)

好的 还没看到*Test类 谢谢解答 :+1:

**Comment by qinkangdeid** [comment]
目前的短信模板配置是只支持单个注入吗？短信发送前置校验是针对全局设置
假如短信发送有多模板   一个scope 一个短信模板code  有对应的发送校验 （发送次数 一天几次 类似的） 是不是就得使用数据库表做配置了？

**Comment by Hippoom** [comment]
尝试理一下“每个Scope指定各自短信模板code”的场景：

```
Given 已注册Scope 'A站短信登录'
And 已指定Scope 'A站短信登录'使用Aliyun Sms Service模板Code '4872'
And 我在A站的注册手机为'1391XXXXX63'
When 我请求短信验证码
Then 我收到Aliyun Sms Service模板Code '4872'样式的短信验证码

Given 已注册Scope 'B站短信登录'
And 已指定Scope 'B站短信登录'使用Aliyun Sms Service模板Code '4873'
And 我在A站的注册手机为'1391XXXXX63'
When 我请求短信验证码
Then 我收到Aliyun Sms Service模板Code '4873'样式的短信验证码
```

如果场景理解正确的话，目前默认的`AliyunSmsVerificationCodeSender`暂时还不支持这样的匹配。关于是否需要数据库配置取决于`SmsVerificationScope`的"自服务"程度。如果`SmsVerificationScope`是可枚举，且不频繁增加的，可以考虑用文件配置；如果希望做到`SmsVerificationScope`自服务申请，那么就需要使用数据库了。

目前的版本，无论哪种方法都可以自定义扩展`SmsVerificationCodeSender`来实现。

**Comment by Hippoom** [comment]
尝试理一下“每个Scope指定各自短信模板code”的场景：

这里是指限流策略对吗？如果是的话，目前的`RateLimitingHandler`的默认实现确实是按全局设置的。这是由于`SmsVerificationScope `是迭代中引入的新概念，其它组件的变化没有跟上。解决方向同上一评论。

**Comment by Hippoom** [comment]
分别建立了
 [Per `SmsVerificationScope` Per Aliyun Sms Template Code](https://github.com/TheBund1st/daming/issues/26)
和[Per `SmsVerificationScope` Per RateLimiter](https://github.com/TheBund1st/daming/issues/27)。如有需要，请移步这两个问题继续讨论，谢谢
